### ISSUE TITLE
Feature Request: Allow selecting a project directory besides the one the map resides in

### ISSUE THREAD

**Issue by mid-kid** [roukaour/polished-map#3]
Sometimes you want to have maps in different folders, and it doesn't work with patches such as this: https://github.com/pret/pokecrystal/pull/386

This feature would greatly improve usability.

**Comment by roukaour** [comment]
When the project directory can be derived from the map directory, it helps usability. You can double-click a .blk to open it automatically, and there's no need to prompt with the badly-designed Windows directory picker.

The way you've structured the maps, it looks like all of them are in maps/*subdirectory*/*MapName*.blk? In that case, you can edit config.h and config.cpp to support a custom project type. Just have it behave like `POKECRYSTAL` for most things, but `project_path_from_blk_path` should behave like `PRISM` (since Prism stores all its maps in maps/blk/\*.blk) and `blk_path_from_project_path` should construct some default path for new maps like `strcat(blk_path, "maps" DIR_SEP "misc" DIR_SEP)`.
